version: "2"

services:

# application data container

  application:
    build: ./application
    volumes:
      - ../:/var/www/laravel

  data:
    build: ./data
    volumes:
      - ../mysql/:/var/lib/mysql

# webserver container

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - application
    links:
      - php-fpm:php

  php-fpm:
    build: ./php-fpm
    volumes_from:
      - application
    links:
      - workspace:workspace

  workspace:
    build: ./workspace
    volumes_from:
      - application
    tty: true


# database container

  mysql:
    build: ./mysql
    volumes_from:
      - data
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: develop
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
      MYSQL_ROOT_PASSWORD: root

